version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./public:/etc/nginx/html
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - nginx_network
  
  app:
    build: ./app
    container_name: app
    ports:
      - 3001:3000
    expose:
      - '3000'
    tty: true
    networks:
      - nginx_network
  
networks:
  nginx_network:
    driver: bridge